// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-variants/EvidenceForward.tsx": () => import("../components/mockups/homepage-variants/EvidenceForward.tsx"),
  "./components/mockups/homepage-variants/WeightedHierarchy.tsx": () => import("../components/mockups/homepage-variants/WeightedHierarchy.tsx")
};
